FROM frolvlad/alpine-oraclejdk8:slim
MAINTAINER nestor.morocco@gmail.com
ADD target/saludo-eureka-naming-server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
